name:                ms-tds
version:             0.4.0.2
github:              "mitsuji/ms-tds"
license:             BSD3
author:              "Takamasa Mitsuji"
maintainer:          "tkms@mitsuji.org"
copyright:           "2019 Takamasa Mitsuji"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            TDS Protocol implemented in Haskell
category:            Database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mitsuji/ms-tds#readme>

##
## for usual
##   with tls recent version, crypton, crypton-x509-store, crypton-x509-system
##
dependencies:
- base >= 4.7 && < 5
- bytestring
- binary >= 0.8.1.0
- mtl
- array
- text
- time
- network
- tls
- data-default-class
- crypton
- crypton-x509-store
- crypton-x509-system
- uuid-types
- template-haskell

##
## for lts-21.25 or less
##   with tls 1.6.0 or less, cryptonite, x509-store, x509-system
##
#dependencies:
#- base >= 4.7 && < 5
#- bytestring
#- binary >= 0.8.1.0
#- mtl
#- array
#- text
#- time
#- network
#- tls
#- data-default-class
#- cryptonite
#- x509-store
#- x509-system
#- uuid-types
#- template-haskell


library:
  source-dirs: src


tests:
  tds-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ms-tds
